<a href="https://colab.research.google.com/github/07HUB17/Python/blob/main/MicrowaveFilter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Microwave Filterの解析

In [7]:
#import
import numpy as np
import math
from matplotlib import pyplot as plt

#param
f0=2
df=0.05
fbw=df/f0
N=3
Lar=0.1

In [8]:
#配列初期化

g_parameter = [0]*(N+2)

In [9]:
# g param (chevichef)
beta=math.log(1/np.tanh(Lar/17.37))
gammma=np.sinh(beta/2/N)

g_parameter[0]=1.0    #g0
g_parameter[1]=2/gammma*np.sin(math.pi/2/N)   #g1

for i in range(2,N+1):
  g_parameter[i]=1/g_parameter[i-1]*4*np.sin((2*i-1)*math.pi/(2*N))*np.sin((2*i-3)*math.pi/(2*N)) \
  /(pow(gammma,2)+pow(np.sin((i-1)*math.pi/N),2))

if N%2==0:
  g_parameter[N+1]=pow(1/np.tanh(beta/4),2)
elif N%2==1.0:
  g_parameter[N+1]=1

print(g_parameter)


[1.0, 1.031585142507876, 1.147400329953722, 1.031585142507876, 1]


In [10]:
#coupling matrix
M=np.zeros((N+2,N+2))
M[0][1]=M[1][0]=1/math.sqrt(g_parameter[0]*g_parameter[1])
for i in range(1,N):
   M[i][i+1]=M[i+1][i]=1/math.sqrt(g_parameter[i]*g_parameter[i+1])
M[N][N+1]=M[N+1][N]=1/math.sqrt(g_parameter[N]*g_parameter[N+1])
print(M)



[[0.         0.98457195 0.         0.         0.        ]
 [0.98457195 0.         0.91915759 0.         0.        ]
 [0.         0.91915759 0.         0.91915759 0.        ]
 [0.         0.         0.91915759 0.         0.98457195]
 [0.         0.         0.         0.98457195 0.        ]]


In [11]:
#coupling factor mij
m_coupling_factor=np.zeros((N+2,N+2))
m_coupling_factor=fbw*M[1:N+1,1:N+1]
Qes=1/pow(M[0][1],2)/fbw
Qel=1/pow(M[N+1][N],2)/fbw
print(Qes)
print(Qel)
print(m_coupling_factor)


41.26340570031503
41.26340570031503
[[0.         0.02297894 0.        ]
 [0.02297894 0.         0.02297894]
 [0.         0.02297894 0.        ]]


In [12]:
fp2=2.03
fp1=1.98

m_coupling_factor_sim=(fp2**2-fp1**2)/(fp2**2+fp1**2)
m_coupling_factor_sim

0.024933779364033057

In [13]:
f0_sim=2
f1=1.983
f2=2.027
df_sim=f2-f1
Qes=f0_sim/df_sim
print(Qes)

45.45454545454542


In [22]:
Z=np.zeros((N+2,N+2))
R=np.zeros((N+2,N+2))
U=np.zeros((N+2,N+2))
R[0][0]=R[N+1][N+1]=1
for i in range(1,N+1):
   U[i][i]=1
Z=R+1j*U+1j*M

In [23]:
print(R)
print(U)
print(Z)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[1.+0.j         0.+0.98457195j 0.+0.j         0.+0.j
  0.+0.j        ]
 [0.+0.98457195j 0.+1.j         0.+0.91915759j 0.+0.j
  0.+0.j        ]
 [0.+0.j         0.+0.91915759j 0.+1.j         0.+0.91915759j
  0.+0.j        ]
 [0.+0.j         0.+0.j         0.+0.91915759j 0.+1.j
  0.+0.98457195j]
 [0.+0.j         0.+0.j         0.+0.j         0.+0.98457195j
  1.+0.j        ]]
